/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-x-altx-alt' : '&#xe000;',
			'icon-untitled' : '&#xe001;',
			'icon-wrench' : '&#xe002;',
			'icon-warning' : '&#xe003;',
			'icon-volume' : '&#xe004;',
			'icon-users' : '&#xe005;',
			'icon-user3' : '&#xe006;',
			'icon-user2' : '&#xe007;',
			'icon-user' : '&#xe008;',
			'icon-unlocked' : '&#xe009;',
			'icon-twitter2' : '&#xe00a;',
			'icon-twitter' : '&#xe00b;',
			'icon-trophy2' : '&#xe00c;',
			'icon-trophy' : '&#xe00d;',
			'icon-tree' : '&#xe00e;',
			'icon-thumbs-up2' : '&#xe00f;',
			'icon-thumbs-up' : '&#xe010;',
			'icon-tag' : '&#xe011;',
			'icon-tablet' : '&#xe012;',
			'icon-stats2' : '&#xe013;',
			'icon-stats' : '&#xe014;',
			'icon-star2' : '&#xe015;',
			'icon-star' : '&#xe016;',
			'icon-spinner2' : '&#xe017;',
			'icon-spinner' : '&#xe018;',
			'icon-signup' : '&#xe019;',
			'icon-search' : '&#xe01a;',
			'icon-screen' : '&#xe01b;',
			'icon-salesforce-sf' : '&#xe01c;',
			'icon-rocket-angle' : '&#xe01d;',
			'icon-remove' : '&#xe01e;',
			'icon-question-mark' : '&#xe01f;',
			'icon-profile' : '&#xe020;',
			'icon-point-up' : '&#xe021;',
			'icon-pointing' : '&#xe022;',
			'icon-podcast' : '&#xe023;',
			'icon-plus' : '&#xe024;',
			'icon-play2' : '&#xe025;',
			'icon-play' : '&#xe026;',
			'icon-play-2' : '&#xe027;',
			'icon-pie' : '&#xe028;',
			'icon-phone' : '&#xe029;',
			'icon-pencil' : '&#xe02a;',
			'icon-pcs' : '&#xe02b;',
			'icon-paste' : '&#xe02c;',
			'icon-new-tab' : '&#xe02d;',
			'icon-newspaper' : '&#xe02e;',
			'icon-move-vertical' : '&#xe02f;',
			'icon-mobile2' : '&#xe030;',
			'icon-mobile' : '&#xe031;',
			'icon-minus' : '&#xe032;',
			'icon-menu' : '&#xe033;',
			'icon-loop' : '&#xe034;',
			'icon-lock' : '&#xe035;',
			'icon-list' : '&#xe036;',
			'icon-linkedin' : '&#xe037;',
			'icon-linegraph' : '&#xe038;',
			'icon-library' : '&#xe039;',
			'icon-laptop' : '&#xe03a;',
			'icon-info' : '&#xe03b;',
			'icon-image' : '&#xe03c;',
			'icon-home' : '&#xe03d;',
			'icon-grid' : '&#xe03e;',
			'icon-google-plus2' : '&#xe03f;',
			'icon-google-plus' : '&#xe040;',
			'icon-fullscreen' : '&#xe041;',
			'icon-floppy' : '&#xe042;',
			'icon-flag' : '&#xe043;',
			'icon-file-pdf' : '&#xe044;',
			'icon-file' : '&#xe045;',
			'icon-feed' : '&#xe046;',
			'icon-facebook2' : '&#xe047;',
			'icon-facebook' : '&#xe048;',
			'icon-exit' : '&#xe049;',
			'icon-envelope' : '&#xe04a;',
			'icon-enter' : '&#xe04b;',
			'icon-document-fill' : '&#xe04c;',
			'icon-diary' : '&#xe04d;',
			'icon-connection' : '&#xe04e;',
			'icon-coin' : '&#xe04f;',
			'icon-cogs' : '&#xe050;',
			'icon-cog' : '&#xe051;',
			'icon-cloud' : '&#xe052;',
			'icon-close' : '&#xe053;',
			'icon-clock2' : '&#xe054;',
			'icon-clock' : '&#xe055;',
			'icon-checkmark' : '&#xe056;',
			'icon-check-alt' : '&#xe057;',
			'icon-chart-alt' : '&#xe058;',
			'icon-chart' : '&#xe059;',
			'icon-camera' : '&#xe05a;',
			'icon-calendar2' : '&#xe05b;',
			'icon-calendar' : '&#xe05c;',
			'icon-bubble' : '&#xe05d;',
			'icon-briefcase' : '&#xe05e;',
			'icon-box-add' : '&#xe05f;',
			'icon-bookmark' : '&#xe060;',
			'icon-bell' : '&#xe061;',
			'icon-bars-alt' : '&#xe062;',
			'icon-bars3' : '&#xe063;',
			'icon-bars2' : '&#xe064;',
			'icon-arrow-up-right' : '&#xe065;',
			'icon-arrow-up-left' : '&#xe066;',
			'icon-arrow-up' : '&#xe067;',
			'icon-arrow-up-2' : '&#xe068;',
			'icon-arrow-right' : '&#xe069;',
			'icon-arrow-right-2' : '&#xe06a;',
			'icon-arrow-left' : '&#xe06b;',
			'icon-arrow-left-2' : '&#xe06c;',
			'icon-arrow-down-right' : '&#xe06d;',
			'icon-arrow-down-left' : '&#xe06e;',
			'icon-arrow-down' : '&#xe06f;',
			'icon-arrow-down-2' : '&#xe070;',
			'icon-alert' : '&#xe071;',
			'icon-alarm2' : '&#xe072;',
			'icon-alarm' : '&#xe073;',
			'icon-aid' : '&#xe074;',
			'icon-shield' : '&#xe075;',
			'icon-menu2' : '&#xe076;',
			'icon-earth' : '&#xe077;',
			'icon-bars' : '&#xe078;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};